name: Go Linter CI

on:
  push:
    branches:
      - api/basketball
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.0

      - name: Install golint
        run: |
          go get -u golang.org/x/lint/golint
          go install golang.org/x/lint/golint

      - name: Run golint
        run: golint ./...
